version: "3"

services:

  matcher:
    image: jeroenvm/zzp-matcher
    networks:
      - traefik-net
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    labels:
      "traefik.port=8080"
      "traefik.docker.network=traefik-net"
      "traefik.backend.loadbalancer.sticky=true"
    deploy:
      replicas: 2

  profile: 
    image: maanenh/zzp-profile-srv
    networks:
      - traefik-net
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    labels:
      "traefik.port=8080"
      "traefik.docker.network=traefik-net"
      "traefik.backend.loadbalancer.sticky=true"
    deploy:
      replicas: 2

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]
  
  portainer:
    image: portainer/portainer
    networks:
      traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      "traefik.port=9000"
      "traefik.docker.network=traefik-net"
      "traefik.backend.loadbalancer.sticky=true"
    placement:
        constraints: [node.role == manager]
        
networks:
  ingress:
    driver: overlay
    external: true
    ipam:
      driver: default
      config:
        - subnet: 10.255.0.0/16
  traefik-net:
    driver: overlay
    external: true
    ipam:
      driver: default
      config:
        - subnet: 10.254.0.0/16
